// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUgkO-Ftpv4h4qDiLHbqRCFpknfWgSw8',
    appId: '1:124605377629:web:9e4a65dc81b09d3299b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    authDomain: 'linen-republic.firebaseapp.com',
    storageBucket: 'linen-republic.appspot.com',
    measurementId: 'G-72FGMTC61H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-g91RY4pjC3LQyAOPo9fLjibS83gSTuQ',
    appId: '1:124605377629:android:3c00a44209ca450099b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    storageBucket: 'linen-republic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVK8f1ATVvbxRhshwas4APL5cQg_t5DIc',
    appId: '1:124605377629:ios:a36917e2d65b7e6699b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    storageBucket: 'linen-republic.appspot.com',
    iosBundleId: 'com.example.linenRepublic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVK8f1ATVvbxRhshwas4APL5cQg_t5DIc',
    appId: '1:124605377629:ios:7f7a5c3680909d5999b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    storageBucket: 'linen-republic.appspot.com',
    iosBundleId: 'com.example.linenRepublic.RunnerTests',
  );
}
